### ISSUE TITLE
Cannot navigate to profile view

### ISSUE THREAD

**Issue by connor11528** [stormpath/stormpath-sdk-angularjs#86]
I have an angular app with the run and config defined:

```
app.config(function($stateProvider, $urlRouterProvider){
    $stateProvider
        .state('main', {
            url: "/",
            templateUrl: "templates/main.html",
            controller: 'MainCtrl'
        })
        .state('register', {
            url: "/register",
            templateUrl: "templates/register.html",
        })
        .state('login', {
            url: "/login",
            templateUrl: "templates/login.html",
        })
        .state('profile', {
            url: '/profile',
            controller: 'ProfileCtrl',
            templateUrl: 'templates/profile.html',
            sp: {
                authenticate: true
            }
        });

    $urlRouterProvider.otherwise("/");
});

app.run(function($stormpath){
  $stormpath.uiRouter({
    loginState: 'login',
    defaultPostLoginState: 'main'
  });
});
```

The ProfileCtrl is empty:

```
app.controller('ProfileCtrl', function($scope){

});
```

Then I navigate to the profile view after login using

```
<li if-user ng-class="{active: isActive('/profile')}">
      <a ng-href="/profile">Profile</a>
  </li>
```

This redirects me to `http://localhost:3000/profile#/` but the profile template does not show up (instead my 'main' template stays showed). I am using node.js for the server side. Why is the profile view not rendering? I can provide the server code if necessary. All I really have there is the `app.use(stormpath.init({})`.

**Comment by connor11528** [comment]
(above) accidentally raised this issue in the express repo, it is meant for this one

**Comment by connor11528** [comment]
Oh snap, maybe it relates to the server side too. Looking in my console I have an error when trying to view profile:

```
TypeError: Cannot read property 'dataStore' of undefined
    at JwtAuthenticator.authenticate (/Users/connorleech/Projects/node-angular-stormpath/node_modules/express-stormpath/node_modules/stormpath/lib/jwt/jwt-authenticator.js:38:32)
    at Object.module.exports [as getUser] (/Users/connorleech/Projects/node-angular-stormpath/node_modules/express-stormpath/lib/helpers/get-user.js:69:19)
    at stormpathMiddleware (/Users/connorleech/Projects/node-angular-stormpath/node_modules/express-stormpath/lib/stormpath.js:92:13)
    at Layer.handle [as handle_request] (/Users/connorleech/Projects/node-angular-stormpath/node_modules/express/lib/router/layer.js:95:5)
    at trim_prefix (/Users/connorleech/Projects/node-angular-stormpath/node_modules/express/lib/router/index.js:312:13)
    at /Users/connorleech/Projects/node-angular-stormpath/node_modules/express/lib/router/index.js:280:7
    at Function.process_params (/Users/connorleech/Projects/node-angular-stormpath/node_modules/express/lib/router/index.js:330:12)
    at next (/Users/connorleech/Projects/node-angular-stormpath/node_modules/express/lib/router/index.js:271:10)
    at /Users/connorleech/Projects/node-angular-stormpath/node_modules/express/lib/router/index.js:618:15
    at next (/Users/connorleech/Projects/node-angular-stormpath/node_modules/express/lib/router/index.js:256:14)
    at cookieParser (/Users/connorleech/Projects/node-angular-stormpath/node_modules/cookie-parser/index.js:40:14)
    at Layer.handle [as handle_request] (/Users/connorleech/Projects/node-angular-stormpath/node_modules/express/lib/router/layer.js:95:5)
    at trim_prefix (/Users/connorleech/Projects/node-angular-stormpath/node_modules/express/lib/router/index.js:312:13)
    at /Users/connorleech/Projects/node-angular-stormpath/node_modules/express/lib/router/index.js:280:7
    at Function.process_params (/Users/connorleech/Projects/node-angular-stormpath/node_modules/express/lib/router/index.js:330:12)
    at next (/Users/connorleech/Projects/node-angular-stormpath/node_modules/express/lib/router/index.js:271:10)
```

**Comment by connor11528** [comment]
I was serving up the files wrong from express. See issue #214 (referenced above)

Starting the web server should look like:

```
/**
 * Start the web server.
 */
app.on('stormpath.ready',function () {
  console.log('Stormpath Ready');
  var port = process.env.PORT || 3000;
  app.listen(port, function () {
    console.log('Application running at http://localhost:'+port);
  });
});
```
